#!/bin/bash

# AdMob Setup Script for Crunchyroll RSS Tracker
# This script helps you securely configure AdMob for your project

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project root directory
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADMOB_PROPERTIES="$PROJECT_ROOT/admob.properties"
ADMOB_TEMPLATE="$PROJECT_ROOT/admob.properties.template"

echo -e "${BLUE}🚀 AdMob Configuration Setup for Crunchyroll RSS Tracker${NC}"
echo "=================================================="

# Check if template exists
if [ ! -f "$ADMOB_TEMPLATE" ]; then
    echo -e "${RED}❌ Error: admob.properties.template not found!${NC}"
    echo "Please make sure you're running this script from the project root directory."
    exit 1
fi

# Check if admob.properties already exists
if [ -f "$ADMOB_PROPERTIES" ]; then
    echo -e "${YELLOW}⚠️  Warning: admob.properties already exists!${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Copy template to create admob.properties
cp "$ADMOB_TEMPLATE" "$ADMOB_PROPERTIES"
echo -e "${GREEN}✅ Created admob.properties from template${NC}"

# Interactive configuration
echo
echo -e "${BLUE}📝 Let's configure your AdMob IDs...${NC}"
echo

# Function to validate AdMob ID format
validate_admob_id() {
    local id="$1"
    local type="$2"

    if [[ ! "$id" =~ ^ca-app-pub-[0-9]{16}[~\/][0-9]{10}$ ]]; then
        echo -e "${RED}❌ Invalid $type format!${NC}"
        echo "Expected format: ca-app-pub-1234567890123456~1234567890 (for App ID)"
        echo "              or ca-app-pub-1234567890123456/1234567890 (for Unit ID)"
        return 1
    fi
    return 0
}

# Get AdMob App ID
while true; do
    echo -e "${YELLOW}📱 Enter your AdMob App ID:${NC}"
    echo "   (Find this in AdMob Console > App settings > App ID)"
    echo "   Format: ca-app-pub-1234567890123456~1234567890"
    read -p "App ID: " ADMOB_APP_ID

    if [ -z "$ADMOB_APP_ID" ]; then
        echo -e "${RED}❌ App ID cannot be empty!${NC}"
        continue
    fi

    if [[ "$ADMOB_APP_ID" == *"REPLACE_WITH_YOUR"* ]]; then
        echo -e "${RED}❌ Please enter your actual AdMob App ID, not the placeholder!${NC}"
        continue
    fi

    if validate_admob_id "$ADMOB_APP_ID" "App ID"; then
        break
    fi
done

# Get Banner Unit ID
while true; do
    echo
    echo -e "${YELLOW}🎯 Enter your AdMob Banner Unit ID:${NC}"
    echo "   (Find this in AdMob Console > Ad units > Banner)"
    echo "   Format: ca-app-pub-1234567890123456/1234567890"
    read -p "Banner Unit ID: " ADMOB_BANNER_UNIT_ID

    if [ -z "$ADMOB_BANNER_UNIT_ID" ]; then
        echo -e "${RED}❌ Banner Unit ID cannot be empty!${NC}"
        continue
    fi

    if [[ "$ADMOB_BANNER_UNIT_ID" == *"REPLACE_WITH_YOUR"* ]]; then
        echo -e "${RED}❌ Please enter your actual Banner Unit ID, not the placeholder!${NC}"
        continue
    fi

    if validate_admob_id "$ADMOB_BANNER_UNIT_ID" "Banner Unit ID"; then
        break
    fi
done

# Optional: Get Interstitial Unit ID
echo
echo -e "${YELLOW}🎬 Enter your AdMob Interstitial Unit ID (optional):${NC}"
echo "   (Press Enter to skip)"
read -p "Interstitial Unit ID: " ADMOB_INTERSTITIAL_UNIT_ID

if [ ! -z "$ADMOB_INTERSTITIAL_UNIT_ID" ] && [[ "$ADMOB_INTERSTITIAL_UNIT_ID" != *"REPLACE_WITH_YOUR"* ]]; then
    if ! validate_admob_id "$ADMOB_INTERSTITIAL_UNIT_ID" "Interstitial Unit ID"; then
        echo -e "${YELLOW}⚠️  Invalid Interstitial Unit ID format, using placeholder${NC}"
        ADMOB_INTERSTITIAL_UNIT_ID="REPLACE_WITH_YOUR_INTERSTITIAL_UNIT_ID"
    fi
else
    ADMOB_INTERSTITIAL_UNIT_ID="REPLACE_WITH_YOUR_INTERSTITIAL_UNIT_ID"
fi

# Ask about ads enabled
echo
echo -e "${YELLOW}💰 Do you want to enable ads in production builds?${NC}"
read -p "Enable ads? (Y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Nn]$ ]]; then
    ADS_ENABLED="false"
else
    ADS_ENABLED="true"
fi

# Update the admob.properties file
echo
echo -e "${BLUE}📝 Writing configuration...${NC}"

cat > "$ADMOB_PROPERTIES" << EOF
# AdMob Configuration
# Generated by setup_admob.sh on $(date)
# DO NOT commit this file to version control

# Your AdMob App ID (found in AdMob console)
ADMOB_APP_ID=$ADMOB_APP_ID

# Your AdMob Banner Unit ID (found in AdMob console)
ADMOB_BANNER_UNIT_ID=$ADMOB_BANNER_UNIT_ID

# Your AdMob Interstitial Unit ID (optional)
ADMOB_INTERSTITIAL_UNIT_ID=$ADMOB_INTERSTITIAL_UNIT_ID

# Enable/disable ads in production (true/false)
ADS_ENABLED=$ADS_ENABLED

# Configuration completed on $(date)
# To reconfigure, run: ./setup_admob.sh
EOF

# Verify .gitignore
if ! grep -q "admob.properties" "$PROJECT_ROOT/.gitignore" 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Adding admob.properties to .gitignore...${NC}"
    echo "" >> "$PROJECT_ROOT/.gitignore"
    echo "# AdMob configuration (contains sensitive IDs)" >> "$PROJECT_ROOT/.gitignore"
    echo "admob.properties" >> "$PROJECT_ROOT/.gitignore"
fi

# Success message
echo
echo -e "${GREEN}🎉 AdMob configuration completed successfully!${NC}"
echo
echo -e "${BLUE}📋 Configuration Summary:${NC}"
echo "   App ID: $ADMOB_APP_ID"
echo "   Banner Unit ID: $ADMOB_BANNER_UNIT_ID"
echo "   Interstitial Unit ID: $ADMOB_INTERSTITIAL_UNIT_ID"
echo "   Ads Enabled: $ADS_ENABLED"
echo
echo -e "${GREEN}✅ Next Steps:${NC}"
echo "   1. Build your project: ./gradlew assembleRelease"
echo "   2. Test with debug build: ./gradlew assembleDebug"
echo "   3. Check logs for 'AdManager' to verify ad loading"
echo
echo -e "${YELLOW}🔒 Security Notes:${NC}"
echo "   • admob.properties is automatically ignored by git"
echo "   • Debug builds use test ads (safe for development)"
echo "   • Release builds use your real AdMob IDs"
echo "   • Never share your AdMob IDs publicly"
echo
echo -e "${BLUE}📚 For detailed setup instructions, see: ADMOB_SETUP.md${NC}"
